name: catch_task_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  intl: ^0.17.0

dev_dependencies:
  csc_picker: ^0.2.6
  flutter_lints: ^1.0.0
  flutter_svg: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_test:
    sdk: flutter
  flutter_toggle_tab: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
